dist: trusty
sudo: false

services:
  - docker

language: java

env:
  global:
 #   - secure: "VqFT1YqUAsqCzi2itsYTHIBnjZoZFSU8xtY/+WCJUqLhEZIyGXCM3A9W7bKG+ZSzhcuIN+qg+qGw0tRR3G2GmLB/G5akPjKMXwstx8VPx7fRlwMaF8LkTd+z8sjlExR1FEjs7zGjEUXlfMUaudgk0SS7xoNpIAgcKY6HcIJsMUHpQ7tuffxEFZeW/xnnH02hNIneVhR7sRgjxI5yfzmbuZ4J1AlPfx/OtriTKRzHdUWZamxd/iuu/lzJC3uhZpXU7vkGjjVCePH+5KgcpAhMCJB4on9U5aMgANllwbCF4dqtIg26NA3dc/CBIH8oVI2jjvMgj3doiV9NAYtJD3CwMbv//zSBhzvm88HRKaaESQ8SIj8rvXU32NGmK/drilpcHfbpg70OnOeyCxkn1Y4wp09wyKA1+URLWCLt35dszIVAVi3dYeAksELpE9RUGcqTjwKb04Np1DM0Aa0IwLGFxS4Bw7hT3XLPHz/qjB29kzRtyQkX88gKa1FsfNTjDAN5IRbuGuhvgz70sy1PppefH+iqrX058K8PTBv543sumP3w+rZR0DL2JpJtZbJ7C8TPzaSOHfzSisfTYmNBRrK8OaI2Cp53pE5Z9eu7x8I5XMIZBMYQCCkTlgQcjxqoW4YyUW+R8/5euNyGP3mCFoSgDZmw9JW7id7/WnRhOStt5rw="
    - secure: "A2DLzy6QD4dP4TvKaMQ5dxSCtHkgoqgupJi+8/rzNFBF8LvTMgJv5aBwOrld9VyCZRy9ON4kKbNIrJn5yaXTjImkrrbziUfYaqQy9o29Ror1HOlMneIOdQDzAoZJ8MRyxKe7sVMRrX5s5hqgE4X9GmX7Si52nq34rhwabag3dV2oec6Cshwgd2YRiUHeLXYdNfQAxgN2aq0FpwKy5mlnVveXQ88e81vOFC/A5EG8SJeGHK4XZ+HvyeGiVXJ68H0grN/B20T6EdpwoIBiwoq15AZNsfKFjIvcZm7lj4C5f3pjgTqUFwujRSAY1OIZphNg3/30S2SzUTZN9oTVUfqNTsJ/lhqxcSwGbihv90lLYjmeSPipI4cxXtG1bDw8aqCHCvyrxIjqd5dc9I40FTrYs+FsTVETYNoeKsdpXvsRP792Sr/FJc3tzfwDgD4NwnhuVOip2PUN5zFIFy+NFlbLim8dQYQABSOWd2UaCRf/zrrNPM7IAKbsnWMfys36C+sBKmjtbkBg79cYkqbx9XObmJY01ZV0Oy6RpfPPoFkM6TL9ejTbMVjQdcWySunSNwWr119oFGIcoIi8fjytpd5O3qxYuu4D1NhPd5/rZZXf1r1RunIQf/L3a1i6umwFFnVREhHittUyldnRiM0M62vB06IQf0z39uJk52lHu5/vIs4="
    - secure: "rZVVYXwmDDBXB6gk2aSG4DQnRec9sO4lDwLLy4uahpcOUr09agrpYWj66MTqd7+PXaCa/kl3cotcK5m3TuwX+S7yjeIXZGzQVR2+6CBbYj2zrIXNTIJjE5apA4Mz5rXDYuZDlybaAI4/5vRXAyC4QIOy7uWJ//54lDIgENQ9BaSSYPGza+YR1dGKAySw9r9zQmj7RY7txXvF8AC6slii6Ik/mj3jx8RBBnhwe/hcD6ZrN51jmWtCX1SMsXvoxAxJ0LQYTD8k2x7NXy0TdOwemj3sS5q2SGt3z6aDNTJMO1Q0PXSkmS94x5wCrN6stPWRuOIVyo7pLUsAcbEBpBpuXz0ROAX+akfU3UGWakepumDNrpR25XfeMUnFoan3wRNV2Uuuyp5obScoCNHXKsYTJti7DbdU+ffJddKy2gLHpdQd0owoGuDwsQrjzQpiTkaRWqQ8Ln6ajiJ9ABeSNPEoKJiHDW9kir8nT6P81Kmz2+r4eGXYLQ+vE3QLo/mQApnv659Drm+8axXSpOKk0cRSqvhM+PUX1qrkDcOIOkJcGHkqx5xRJ1AdSVXm0rxrqVPizIzNPskiOxlddAnnNumI1PFnr2Kj6QFy9p0CwK7yv3hwBGXdWcVNcLZUxFEJI7Q1ixMSDacQwEmRh/8PTeS5kdsZxCxDlVyJjvv1Oly4qdQ="
    - REPO=tellef/allure
    - COMMIT=${TRAVIS_COMMIT::8}
    - VERSION=`date +%y.%-m.dev${COMMIT}`

script:
  - ./gradlew build
  - docker build -t $REPO:$VERSION .

after_success:
  - echo "Test Success $REPO:$VERSION - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"

deploy:
  - provider: script
    script: 
      - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
      - docker tag $REPO:$VERSION $REPO:latest
      - docker push $REPO
      - docker logout
    on:
      branch: master
      condition:  $TRAVIS_PULL_REQUEST = false
      